
[ClassVersion("1.0.0.0"), FriendlyName("ArcGIS_PortalUnregister")]
class ArcGIS_PortalUnregister : OMI_BaseResource
{
	[Key] String PortalEndPoint;
	[Key] String StandbyMachine;
	[Write, EmbeddedInstance("MSFT_Credential")] String PortalAdministrator;
	[Write] String Version;
};
