[ClassVersion("1.0.0.0"), FriendlyName("ArcGIS_NotebookServerUpgrade")]
class ArcGIS_NotebookServerUpgrade : OMI_BaseResource
{
	[Key] String ServerHostName;
	[Write] String Version;
	[Write, ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
};

