
[ClassVersion("1.0.0.0"), FriendlyName("ArcGIS_DataStore")]
class ArcGIS_DataStore : OMI_BaseResource
{
	[Write] String DatastoreMachineHostName;
	[Key] String ServerHostName;
	[Write, ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
	[Write, EmbeddedInstance("MSFT_Credential")] String SiteAdministrator;
	[Write, EmbeddedInstance("MSFT_Credential")] String RunAsAccount;
	[Write] String ContentDirectory;
	[Write] String DatabaseBackupsDirectory;
	[Write] String FileShareRoot;
	[Write] String DataStoreTypes[];
	[Write, Description("Is Standby instance")] Boolean IsStandby;
	[Write, Description("Is Tile Cache DataStore Clustered")] Boolean IsTileCacheDataStoreClustered;
	[Write, Description("Is Environment Azure")] Boolean IsEnvAzure;
	[Write, ValueMap{"Enabled","Disabled","NotManaged"}, Values{"Enabled","Disabled","NotManaged"}] String PITRState;
};

