
[ClassVersion("1.0.0.0"), FriendlyName("ArcGIS_MissionServerSettings")]
class ArcGIS_MissionServerSettings : OMI_BaseResource
{
    [Write] String ServerHostName;
    [Key] String WebContextURL;
    [Write] String WebSocketContextURL;
	[Write, EmbeddedInstance("MSFT_Credential")] String SiteAdministrator;
    [Write, Description("Is Service Directory Disabled")] Boolean DisableServiceDirectory;
    [Write] String HttpProxyHost;
    [Write] UInt32 HttpProxyPort;
    [Write, EmbeddedInstance("MSFT_Credential")] String HttpProxyCredential;
    [Write] String HttpsProxyHost;
    [Write] UInt32 HttpsProxyPort;
    [Write, EmbeddedInstance("MSFT_Credential")] String HttpsProxyCredential;
    [Write] String NonProxyHosts;
};
