
[ClassVersion("1.0.0.0"), FriendlyName("")]
class ArcGIS_ServerWait : OMI_BaseResource
{
	[Key] String SiteName;
	[Write, ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;    
	[Write, EmbeddedInstance("MSFT_Credential")] String SiteAdministrator;    
        [Write] String ServerHostName;
	[Write,Description("Interval in seconds for retries.")] uint32 RetryIntervalSec;
	[Write,Description("Number of times to retry.")] uint32 RetryCount;
};

