[ClassVersion("1.0.0.0"), FriendlyName("ArcGIS_MissionServerUpgrade")]
class ArcGIS_MissionServerUpgrade : OMI_BaseResource
{
	[Key] String ServerHostName;
	[Write] String Version;
	[Write, ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
};

