
[ClassVersion("1.0.0.0"), FriendlyName("ArcGIS_Server_TLS")]
class ArcGIS_Server_TLS : OMI_BaseResource
{
	[Write] String ServerHostName;
	[Key] String SiteName;
	[Write, ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
	[Write, EmbeddedInstance("MSFT_Credential")] String SiteAdministrator;
	[Write, Description("Location of the .pfx certificate file")] String CertificateFileLocation;
	[Write, EmbeddedInstance("MSFT_Credential"), Description("Password or Private Key for the Certificate")] String CertificatePassword;
    [Write, Description("Common Name for the SSL Certificate")] String CName;
	[Write, Description("Endpoint for the Portal in a WebGIS Deployment")] String PortalEndPoint;
    [Write, Description("EnableSSL")] Boolean EnableSSL;
	[Write, Description("Whether the Certificate should only be imported and not set as the Web Server Certificate Alias")] Boolean ImportOnly;
	[Write, Description("List of RootOrIntermediate Certificates")] String SslRootOrIntermediate;
	[Write, Description("ServerType")] String ServerType;
};

