
[ClassVersion("1.0.0.0"), FriendlyName("ArcGIS_Server_TLS")]
class ArcGIS_Server_TLS : OMI_BaseResource
{
	[Key] String ServerHostName;
	[Write, Description("ServerType")] String ServerType;
	[Write, EmbeddedInstance("MSFT_Credential")] String SiteAdministrator;
	[Write, Description("Web Server Certificate Alias for the SSL Certificate")] String WebServerCertificateAlias;
	[Write, Description("Location of the .pfx certificate file")] String CertificateFileLocation;
	[Write, EmbeddedInstance("MSFT_Credential"), Description("Password or Private Key for the Certificate")] String CertificatePassword;
    [Write, Description("List of RootOrIntermediate Certificates")] String SslRootOrIntermediate;
	[Write, Description("Enable Only HTTPS")] Boolean EnableHTTPSOnly;
	[Write, Description("Enable HTTP Strict Transport Security (HSTS)")] Boolean EnableHSTS;
};

