
[ClassVersion("1.0.0.0"), FriendlyName("ArcGIS_ReverseProxy_ARR")]
class ArcGIS_ReverseProxy_ARR : OMI_BaseResource
{
	[Write] String ServerHostNames[];
	[Key] String ExternalDNSName;
	[Key] String ServerSiteName;
	[Write] String PortalHostNames[];
	[Write] String ServerEndPoint;
	[Write] String PortalEndPoint;
	[Key] String PortalSiteName;
	[Write, ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
	[Write, EmbeddedInstance("MSFT_Credential")] String SiteAdministrator;
	[Write, EmbeddedInstance("MSFT_Credential")] String PortalAdministrator;
	[Write, Description("Enable Failed Request Tracking on IIS")] Boolean EnableFailedRequestTracking;
	[Write, Description("Enable GeoEvent Endpoint URL Rewrite Rules")] Boolean EnableGeoEventEndpoints;
	[Write, Description("Enable Notebook Server Endpoint URL Rewrite Rules")] Boolean EnableNotebookServerEndpoints;
};

