
[ClassVersion("1.0.0.0"), FriendlyName("ArcGIS_LogHarvester")]
class ArcGIS_LogHarvester : OMI_BaseResource
{
	[Write] String HostName;
	[Key, ValueMap{"Server"}, Values{"Server"}] String ComponentType;
	[Write] String Version;
	[Write, Description("Enable Harvester Plugin for Server and Service Logs")] Boolean EnableLogHarvesterPlugin;
	[Write] String LogOutputFolder;
	[Write, ValueMap{"csv","json"}, Values{"csv","json"}] String LogFormat;
};
