
[ClassVersion("1.0.0.0"), FriendlyName("ArcGIS_Portal_TLS")]
class ArcGIS_Portal_TLS : OMI_BaseResource
{
	[Key] String SiteName;
	[Write, ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
	[Write, EmbeddedInstance("MSFT_Credential")] String SiteAdministrator;
	[Write, Description("Location of the .pfx certificate file")] String CertificateFileLocation;
	[Write, EmbeddedInstance("MSFT_Credential"), Description("Password or Private Key for the Certificate")] String CertificatePassword;
    [Write, Description("Common Name for the SSL Certificate")] String CName;
	[Write, Description("Endpoint for the Portal in a WebGIS Deployment")] String PortalEndPoint;
	[Write, Description("Endpoint for the Portal in a WebGIS Deployment")] String ServerEndPoint;
	[Write, Description("List of RootOrIntermediate Certificates")] String SslRootOrIntermediate;
};

