
[ClassVersion("1.0.0.0"), FriendlyName("ArcGIS_Portal_TLS")]
class ArcGIS_Portal_TLS : OMI_BaseResource
{
	[Key] String PortalHostName;
	[Write, EmbeddedInstance("MSFT_Credential")] String SiteAdministrator;
	[Write, Description("Location of the .pfx certificate file")] String CertificateFileLocation;
	[Write, EmbeddedInstance("MSFT_Credential"), Description("Password or Private Key for the Certificate")] String CertificatePassword;
    [Write, Description("Portal Web Server SSL Certificate Alias")] String WebServerCertificateAlias;
	[Write, Description("List of RootOrIntermediate Certificates")] String SslRootOrIntermediate;
	[Write, Description("Enable HTTP Strict Transport Security (HSTS)")] Boolean EnableHSTS;
};

