
[ClassVersion("1.0.0.0"), FriendlyName("ArcGIS_WebAdaptorInstall")]
class ArcGIS_WebAdaptorInstall: OMI_BaseResource
{
	[Key] String Context;
	[Key] String Version;
	[Write] String Path;
	[Write] String Arguments;
	[Write] String LogPath;
	[Write] String SevenZipMsiInstallerPath;
	[Write] String SevenZipInstallDir;
	[Write, ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
};

