
[ClassVersion("1.0.0.0"), FriendlyName("ArcGIS_NotebookServerSettings")]
class ArcGIS_NotebookServerSettings : OMI_BaseResource
{
    [Write] String ServerHostName;
    [Key] String WebContextURL;
	[Write, EmbeddedInstance("MSFT_Credential")] String SiteAdministrator;
    [Write, Description("Is Service Directory Disabled")] Boolean DisableServiceDirectory;
};
