
[ClassVersion("1.0.0.0"), FriendlyName("ArcGIS_License")]
class ArcGIS_License : OMI_BaseResource
{
	[Key] String LicenseFilePath;
	[Write, Description("Optional License Password if applicable"), EmbeddedInstance("MSFT_Credential")] String LicensePassword;
	[Write, Description("Optional Version associated with License (If using License Manger)")] String Version;
	[Write, ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
	[Write, ValueMap{"Server","Portal","Desktop","Pro","LicenseManager","Monitor"}, Values{"Server","Portal","Desktop","Pro","LicenseManager","Monitor"}] String Component;
	[Write, ValueMap{"ImageServer","GeoEvent","GeoAnalytics","GeneralPurposeServer","HostingServer", "NotebookServer","MissionServer","WorkflowManagerServer","KnowledgeServer","VideoServer"}, Values{"ImageServer","GeoEvent","GeoAnalytics","GeneralPurposeServer","HostingServer","NotebookServer","MissionServer","WorkflowManagerServer","KnowledgeServer","VideoServer"}] String ServerRole;
	[Write] String AdditionalServerRoles[];
	[Write, Description("Is Pro or Desktop using Single Use License")] Boolean IsSingleUse;
	[Write, Description("Forcing to License")] Boolean Force;
};

