
[ClassVersion("1.0.0.0"), FriendlyName("ArcGIS_Service_Account")]
class ArcGIS_Service_Account : OMI_BaseResource
{
	[Key] String Name;
	[Write, EmbeddedInstance("MSFT_Credential")] String RunAsAccount;
	[Write] Boolean ForceRunAsAccountUpdate;
	[Write] String DataDir[];
	[Write, ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
	[Write] Boolean IsDomainAccount;
	[Write] Boolean IsMSAAccount;
	[Write] Boolean SetStartupToAutomatic;
};

