[ClassVersion("1.0.0.0"), FriendlyName("ArcGIS_Server_Service")]
class ArcGIS_Server_Service : OMI_BaseResource
{
	[Key] String ServerHostName;	
    [Key] String PathToSourceFile;
	[Write] String ServiceName;
	[Write] String ServiceType;
	[Write] String Folder;
	[Write] String ServerContext;
	[Write] uint32 Port;
	[Write, ValueMap{"STARTED","STOPPED"}, Values{"STARTED","STOPPED"}] String State;
	[Write, ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
	[Write, EmbeddedInstance("MSFT_Credential")] String PublisherAccount;
    [Write] String PathToItemInfoFile;
	[Write] String PortalHostName;
	[Write] uint32 PortalPort;
	[Write] String PortalContext;
};
