
[ClassVersion("1.0.0.0"), FriendlyName("ArcGIS_Portal")]
class ArcGIS_Portal : OMI_BaseResource
{
	[Key] String Version;
	[Key] String PortalHostName;
	[Write, ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
	[Write] String LicenseFilePath;
	[Write] String UserLicenseTypeId;
	[Write, EmbeddedInstance("MSFT_Credential")] String PortalAdministrator;
	[Write] String AdminEmail;
	[Write] String AdminFullName;
	[Write] String AdminDescription;
	[Write, EmbeddedInstance("MSFT_Credential")] String AdminSecurityQuestionCredential;
	[Write, Description("Is Joining Existing site")] Boolean Join;
	[Write, Description("Is HA Portal")] Boolean IsHAPortal;
	[Write, Description("Set logging to debug")] Boolean EnableDebugLogging;
	[Write, Description("LogLevel")] String LogLevel;
	[Write] String PeerMachineHostName;
	[Write] String ContentDirectoryLocation;

	[Write, ValueMap{"None","Azure","AWS"}, Values{"None","Azure","AWS"}, Description("Cloud Storage Type")] String CloudProvider;
	
	[Write, ValueMap{"AccessKey","IAMRole","None"}, Values{"AccessKey","IAMRole","None"}] String AWSAuthenticationType;
	[Write] String AWSRegion;
	[Write] String AWSS3ContentBucketName;
	[Write, EmbeddedInstance("MSFT_Credential")] String AWSAccessKeyCredential;

	[Write, ValueMap{"AccessKey","ServicePrincipal","UserAssignedIdentity","SASToken","None"}, Values{"AccessKey","ServicePrincipal","UserAssignedIdentity","SASToken","None"}] String AzureAuthenticationType;
	[Write] String AzureContentBlobContainerName;
	[Write, EmbeddedInstance("MSFT_Credential")] String AzureStorageAccountCredential;
	[Write, EmbeddedInstance("MSFT_Credential")] String AzureServicePrincipalCredential;
	[Write] String AzureServicePrincipalTenantId;
	[Write] String AzureServicePrincipalAuthorityHost;
	[Write] String AzureUserAssignedIdentityClientId;
	
	[Write] Boolean EnableCreateSiteDebug;
};

