
[ClassVersion("1.0.0.0"), FriendlyName("ArcGIS_Portal")]
class ArcGIS_Portal : OMI_BaseResource
{
	[Key] String PortalEndPoint;
	[Write] String PortalContext;
	[Write] String ExternalDNSName;
	[Write, ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
	[Write, EmbeddedInstance("MSFT_Credential")] String PortalAdministrator;
	[Write] String AdminEMail;
	[Write] Uint8 AdminSecurityQuestionIndex;
	[Write] String AdminSecurityAnswer;
	[Write, Description("Is Joining Existing site")] Boolean Join;
	[Write, Description("Is HA Portal")] Boolean IsHAPortal;
	[Write, Description("Is ReIndexing Existing site After Upgrade")] Boolean UpgradeReindex;
	[Write, Description("Set logging to debug")] Boolean EnableDebugLogging;
	[Write, Description("LogLevel")] String LogLevel;
	[Write] String PeerMachineHostName;
	[Write] String ContentDirectoryLocation;
	[Write] String ContentDirectoryCloudConnectionString;
    [Write] String ContentDirectoryCloudContainerName;    
	[Write, EmbeddedInstance("MSFT_Credential")] String ADServiceUser;
	[Write] Boolean EnableAutomaticAccountCreation;
};

