
[ClassVersion("1.0.0.0"), FriendlyName("ArcGIS_WebAdaptor")]
class ArcGIS_WebAdaptor : OMI_BaseResource
{
	[Write] String Version;
	[Key, ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
	[Key, ValueMap{"Server","NotebookServer","MissionServer","VideoServer","Portal"}, Values{"Server","NotebookServer","MissionServer","VideoServer","Portal"}] String Component;
	[Write] String HostName;
	[Key] String ComponentHostName;
	[Key] String Context;
	[Write] Boolean OverwriteFlag;
	[Write] Boolean AdminAccessEnabled;
	[Write] Boolean IsJavaWebAdaptor;
	[Write, EmbeddedInstance("MSFT_Credential")] String SiteAdministrator;
	[Write] String JavaWebServerWebAppDirectory;
};


