
[ClassVersion("1.0.0.0"), FriendlyName("ArcGIS_TLSCertificateImport")]
class ArcGIS_TLSCertificateImport : OMI_BaseResource
{
	[Key] String HostName;	
	[Key] String ApplicationPath;
	[Key] uint32 HttpsPort;
	[Write, ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
	[Write, EmbeddedInstance("MSFT_Credential")] String SiteAdministrator;
	[Key, ValueMap{"CurrentUser","LocalMachine"}, Values{"CurrentUser","LocalMachine"}] String StoreLocation;
	[Key, ValueMap{"AuthRoot","CertificateAuthority","My","Root","Trust"}, Values{"AuthRoot","CertificateAuthority","My","Root","Trust"}] String StoreName;
	[Write, Description("ServerType")] String ServerType;
};

