
[ClassVersion("1.0.0.0"), FriendlyName("ArcGIS_PortalSettings")]
class ArcGIS_PortalSettings : OMI_BaseResource
{
	[Key] String PortalHostName;
	[Write, EmbeddedInstance("MSFT_Credential")] String PortalAdministrator;
	[Write] String ExternalDNSName;
	[Write] String PortalContext;
	[Write] String PortalEndPoint;
	[Write] String PortalEndPointPort;
	[Write] String PortalEndPointContext;
	[Write, EmbeddedInstance("MSFT_Credential")] String ADServiceUser;
	[Write] Boolean EnableAutomaticAccountCreation;   
	[Write] String DefaultUserLicenseTypeIdForUser;
	[Write] String DefaultRoleForUser;
	[Write, Description("Is Service Directory Disabled")] Boolean DisableServiceDirectory;
	[Write, Description("Disable anonymous access to Portal")] Boolean DisableAnonymousAccess; 
	[Write] Boolean EnableEmailSettings;
	[Write] String EmailSettingsSMTPServerAddress;
	[Write] String EmailSettingsFrom;
	[Write] String EmailSettingsLabel;
	[Write] Boolean EmailSettingsAuthenticationRequired;
	[Write, EmbeddedInstance("MSFT_Credential")] String EmailSettingsCredential;
	[Write] Uint64 EmailSettingsSMTPPort;
	[Write, ValueMap{"SSL","TLS","NONE"}, Values{"SSL","TLS","NONE"}] String EmailSettingsEncryptionMethod;
};

