
[ClassVersion("1.0.0.0"), FriendlyName("ArcGIS_IIS_TLS")]
class ArcGIS_IIS_TLS : OMI_BaseResource
{
	[Key] Uint32 WebSiteId;	
	[Key] String ExternalDNSName;	
	[Write, ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;	
	[Write, Description("Location of the .pfx certificate file")] String CertificateFileLocation;
	[Write, EmbeddedInstance("MSFT_Credential"), Description("Password or Private Key for the Certificate")] String CertificatePassword;
};

