
[ClassVersion("1.0.0.0"), FriendlyName("ArcGIS_DataStoreItem")]
class ArcGIS_DataStoreItem : OMI_BaseResource
{
	[Key] String Name;
	[Write] String SiteName;
	[Write] String HostName;
	[Write] String Port;
	[Write, ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
	[Write, EmbeddedInstance("MSFT_Credential")] String SiteAdministrator;
	[Write, ValueMap{"Folder","CloudStore","RasterStore","BigDataFileShare"}, Values{"Folder","CloudStore","RasterStore","BigDataFileShare"}] String DataStoreType;
	[Write] String DataStoreConnectionString;
	[Write] String DataStoreEndpoint;
	[Write] String DataStorePath;
	[Write] String DataStoreTable;
};

