
[ClassVersion("1.0.0.0"), FriendlyName("ArcGIS_DataStoreItemServer")]
class ArcGIS_DataStoreItemServer : OMI_BaseResource
{
	[Key] String Name;
	[Write] String ServerSiteName;
	[Write] String ServerHostName;
	[Write] String ServerHostPort;
	[Write, EmbeddedInstance("MSFT_Credential")] String SiteAdministrator;
	[Write, ValueMap{"Folder","CloudStore","RasterStore","BigDataFileShare"}, Values{"Folder","CloudStore","RasterStore","BigDataFileShare"}] String DataStoreType;
	[Write] String ConnectionString;
	[Write, EmbeddedInstance("MSFT_Credential")] String ConnectionSecret;
	[Write] Boolean ForceUpdate;
};