
[ClassVersion("1.0.0.0"), FriendlyName("ArcGIS_FileShare")]
class ArcGIS_FileShare : OMI_BaseResource
{
	[Key] String FileShareName;
	[Write] String FileShareLocalPath;
	[Write, EmbeddedInstance("MSFT_Credential")] String Credential;
	[Write] Boolean IsDomainAccount;
	[Write] Boolean IsMSAAccount;
	[Write] String FilePaths;
	[Write, ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
};

