
[ClassVersion("1.0.0.0"), FriendlyName("ArcGIS_Federation")]
class ArcGIS_Federation : OMI_BaseResource
{
	[Key] String PortalHostName;
	[Write] uint32 PortalPort;
	[Write] String PortalContext;
	[Key] String ServiceUrlHostName;
	[Write] uint32 ServiceUrlPort;
	[Write] String ServiceUrlContext;
	[Write] String ServerSiteAdminUrlHostName;
	[Write] uint32 ServerSiteAdminUrlPort;
	[Write] String ServerSiteAdminUrlContext;
	[Write, ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
	[Write] String ServerFunctions;
	[Write] String ServerRole;
	[Write, EmbeddedInstance("MSFT_Credential")] String SiteAdministrator;
	[Write, EmbeddedInstance("MSFT_Credential")] String RemoteSiteAdministrator;
};

