
[ClassVersion("1.0.0.0"), FriendlyName("ArcGIS_InstallPatch")]
class ArcGIS_InstallPatch : OMI_BaseResource
{
	[Key] String Name;
	[Write] String PatchesDir;
	[Key] String Version;
	[Write, ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
};

