
[ClassVersion("1.0.0.0"), FriendlyName("ArcGIS_Install")]
class ArcGIS_Install : OMI_BaseResource
{
	[Key] String Name;
	[Write] String Path;
	[Key] String Version;
	[Write] String Arguments;
	[Write] String LogPath;
	[Write, ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
	[Write] String PatchesDir;
};

