
[ClassVersion("1.0.0.0"), FriendlyName("ArcGIS_DFS")]
class ArcGIS_DFS : OMI_BaseResource
{
	[Key] String DomainName;
	[Write] String FileSharePath;
	[Write] String FileShareName;
	[Write] String ReplicationGroupName;
	[Write, EmbeddedInstance("MSFT_Credential")] String AdminCredentials;
	[Write] String ReplicationNodeNames[];
	[Write, ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
};

